// Auto-generated by update-patterns.py
const PATTERN_LIST = [
	"hor_half",
	"hor_third",
	"hor_third_h2",
	"hor_third_h3_split",
	"parabola_up_0",
	"parabola_down_0",
	"parabola_n_0",
	"parabola_u_0",
];
