// Auto-generated by update-patterns.py
const PATTERN_LIST = [
	"linear_line",
	"grid",
	"rows",
	"columns",
	"parabola_u",
	"parabola_n",
	"parabola_up",
	"parabola_down",
	"hor_third_h3_split",
	"hor_third_h2",
	"hor_third",
	"hor_half",
];
