#!/usr/bin/env python3
"""
Automatically generates pattern-list.js from the patterns directory.
Run this script after adding, renaming, or deleting pattern files.
"""

import os
import json


def main():
    # Get all .js files from the patterns directory
    patterns_dir = "patterns"
    pattern_files = []

    if os.path.exists(patterns_dir):
        for filename in sorted(os.listdir(patterns_dir)):
            if filename.endswith(".js"):
                # Remove the .js extension to get the pattern name
                pattern_name = filename[:-3]
                pattern_files.append(pattern_name)

    # Generate the JavaScript content
    js_content = "// Auto-generated by update-patterns.py\n"
    js_content += "const PATTERN_LIST = [\n"

    for i, pattern in enumerate(pattern_files):
        js_content += f'\t"{pattern}"'
        if i < len(pattern_files) - 1:
            js_content += ","
        js_content += "\n"

    js_content += "];"

    # Write to pattern-list.js
    with open("pattern-list.js", "w") as f:
        f.write(js_content)

    print(f"Generated pattern-list.js with {len(pattern_files)} patterns:")
    for pattern in pattern_files:
        print(f"  - {pattern}")


if __name__ == "__main__":
    main()
