#!/usr/bin/env python3
"""
Automatically generates pattern-list.js from the patterns directory.
Run this script after adding, renaming, or deleting pattern files.
Sorts patterns by CREATED timestamp (newest first).
"""

import os
import re


def main():
    # Get all .js files from the patterns directory with their timestamps
    patterns_dir = "patterns"
    pattern_data = []

    if os.path.exists(patterns_dir):
        for filename in os.listdir(patterns_dir):
            if filename.endswith(".js"):
                # Remove the .js extension to get the pattern name
                pattern_name = filename[:-3]
                filepath = os.path.join(patterns_dir, filename)

                # Read file to find CREATED timestamp
                timestamp = None
                try:
                    with open(filepath, "r") as f:
                        content = f.read()
                        # Look for CREATED=([0-9]+) pattern
                        match = re.search(r"CREATED=([0-9]+)", content)
                        if match:
                            timestamp = int(match.group(1))
                except Exception as e:
                    print(f"Warning: Could not read {filename}: {e}")

                # If no timestamp found, use 0 (will sort to end)
                if timestamp is None:
                    timestamp = 0
                    print(f"Warning: No CREATED timestamp found in {filename}")

                pattern_data.append((timestamp, pattern_name))

    # Sort by timestamp (newest first)
    pattern_data.sort(key=lambda x: x[0], reverse=True)

    # Generate the JavaScript content
    js_content = "// Auto-generated by update-patterns.py\n"
    js_content += "const PATTERN_LIST = [\n"

    for i, (timestamp, pattern) in enumerate(pattern_data):
        js_content += f'\t"{pattern}"'
        if i < len(pattern_data) - 1:
            js_content += ","
        js_content += "\n"

    js_content += "];"

    # Write to pattern-list.js
    with open("pattern-list.js", "w") as f:
        f.write(js_content)

    print(
        f"Generated pattern-list.js with {len(pattern_data)} patterns (sorted newest first):"
    )
    for timestamp, pattern in pattern_data:
        if timestamp > 0:
            print(f"  - {pattern} (timestamp: {timestamp})")
        else:
            print(f"  - {pattern} (no timestamp)")


if __name__ == "__main__":
    main()
